//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDB
    {
        public int Id { get; set; }
        public string note { get; set; }
        public string lokation { get; set; }
        public string ejer { get; set; }
        public string afdeling { get; set; }
        public string maerke { get; set; }
        public string model { get; set; }
        public string pris { get; set; }
    }
}
